[package]
name = "tex-fmt"
version = "0.2.0"
authors = ["William George Underwood"]
license = "MIT"
repository = "https://github.com/WGUNDERWOOD/tex-fmt"
edition = "2021"
description = "LaTeX formatter written in Rust"

[dependencies]
clap = { version = "=4.4.0", features = ["derive"] }
env_logger = "0.11.3"
lazy_static = "1.4.0"
log = "0.4.21"
regex = "1.10.3"
rstest = "0.19.0"
rstest_reuse = "0.6.0"
