[package]
name = "tex-fmt"
version = "0.3.0"
authors = ["William George Underwood"]
license = "MIT"
repository = "https://github.com/WGUNDERWOOD/tex-fmt"
edition = "2021"
description = "LaTeX formatter written in Rust"
exclude = ["tests/*", "extra/*", "*.nix", ".github/*"]

[dependencies]
clap = { version = "4.4.0", features = ["derive"] }
env_logger = "0.11.3"
lazy_static = "1.4.0"
log = "0.4.21"
regex = "1.10.3"
similar = "2.5.0"

[profile.release]
codegen-units = 1
