[package]
name = "tex-fmt"
version = "0.5.2"
authors = ["William George Underwood"]
license = "MIT"
repository = "https://github.com/WGUNDERWOOD/tex-fmt"
edition = "2021"
description = "LaTeX formatter written in Rust"
keywords = ["latex", "formatter"]
categories = ["command-line-utilities", "development-tools"]
exclude = ["tests/*", "extra/*", "*.nix", ".github/*", "completion/*", "man/*"]

[dependencies]
clap = { version = "4.5.23", features = ["cargo"] }
clap_complete = "4.5.40"
clap_mangen = "0.2.24"
colored = "2.2.0"
dirs = "5.0.1"
env_logger = "0.11.6"
lazy_static = "1.5.0"
log = "0.4.22"
merge = "0.1.0"
regex = "1.11.1"
similar = "2.6.0"
toml = "0.8.19"

[features]
shellinstall = []

[build-dependencies]
clap = { version = "4.5.23", features = ["cargo"] }
clap_complete = "4.5.40"
clap_mangen = "0.2.24"

[profile.release]
codegen-units = 1
