[package]
name = "tex-fmt"
license = "MIT"
version = "0.1.0"
edition = "2021"
description = "LaTeX formatter written in Rust"

[dependencies]
clap = { version = "=4.4.0", features = ["derive"] }
env_logger = "0.11.3"
lazy_static = "1.4.0"
log = "0.4.21"
once_cell = "1.19.0"
regex = "1.10.3"
rstest = "0.19.0"
rstest_reuse = "0.6.0"
