[package]
name = "tex-fmt"
version = "0.3.0"
authors = ["William George Underwood"]
license = "MIT"
repository = "https://github.com/WGUNDERWOOD/tex-fmt"
edition = "2021"
description = "LaTeX formatter written in Rust"
keywords = ["latex", "formatter"]
categories = ["command-line-utilities", "development-tools"]
exclude = ["tests/*", "extra/*", "*.nix", ".github/*"]

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
env_logger = "0.11.5"
lazy_static = "1.5.0"
log = "0.4.22"
regex = "1.10.6"
similar = "2.6.0"

[profile.release]
codegen-units = 1
