[package]
name = "tex-fmt"
version = "0.4.6"
authors = ["William George Underwood"]
license = "MIT"
repository = "https://github.com/WGUNDERWOOD/tex-fmt"
edition = "2021"
description = "LaTeX formatter written in Rust"
keywords = ["latex", "formatter"]
categories = ["command-line-utilities", "development-tools"]
exclude = ["tests/*", "extra/*", "*.nix", ".github/*"]

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
clap-serde-derive = "0.2.1"
colored = "2.1.0"
config = "0.14.1"
env_logger = "0.11.5"
lazy_static = "1.5.0"
log = "0.4.22"
path-absolutize = "3.1.1"
regex = "1.11.1"
serde = "1.0.214"
similar = "2.6.0"
toml = "0.8.19"
twelf = { version = "0.15.0", default-features = false, features = ["clap", "toml"] }

[profile.release]
codegen-units = 1
lto = true
